### PR TITLE
My entry for the 1BRC challenge

### PR DESCRIPTION
**Pull request by MichelSchudel**
Implementation class: CalculateAverage_MichelSchudel
JDK Build: latetst OpenJDK 21 is fine
The execution time of the program on your system: About 1 minute 29 seconds (Intel I7 generation 2, 8 cores, 16GB ram), so it's an old beast :-)

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Could you please take a look at the test failures reported by

```
./test.sh MichelSchudel
```

And remove the "test failure" label once done? Thx!

**Comment by gunnarmorling** [comment]
Also please make sure to apply the changes done by the code formatter. Thx!

**Comment by gunnarmorling** [comment]
Hey @MichelSchudel, I'm gonna close this one for now as I haven't heard back, and I need to clean up the slate a bit. Please feel free to create a new PR (based off of latest main), once everything has been addressed. Thanks a lot!

**Comment by MichelSchudel** [comment]
Yeah, that's fine with me. I haven't got lots of time to work on it, and I
see some really awesome results on the leaderboard I can't compete with.
Thanks for taking the time though!

**Pull request closed without merging**
