### PR TITLE
Simple, slow but very short. :-)

### PR DESCRIPTION
**Pull request by alesj**
#### Check List:
- [x] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x] Output matches that of `calculate_average_baseline.sh`
* Execution time:
* Execution time of reference implementation:

real	1m3.460s
user	5m3.568s
sys	0m11.780s

### CODE REVIEW

**Comment by gunnarmorling** [comment]
01:08.311 on the new eval box. Very concise indeed :)

**Comment by gunnarmorling** [comment]
It fails one of the tests though:

```
Validating calculate_average_alesj.sh -- src/test/resources/samples/measurements-3.txt

real	0m0.103s
user	0m0.137s
sys	0m0.034s
1c1
< {Bosaso=-5.0/6.7/20.0, Petropavlovsk-Kamchatsky=9.5/0.0/9.5}
---
> {Bosaso=-15.0/1.3/20.0, Petropavlovsk-Kamchatsky=-9.5/0.0/9.5}
```

The `computeIfAbsent()` call may require some care to make sure it doesn't miss any values?

**Comment by gunnarmorling** [comment]
True. But `DoubleSummaryStatistics` isn't thread-safe?

**Comment by gunnarmorling** [comment]
Btw TIL about `DoubleSummaryStatistics`, nice one.

**Comment by alesj** [comment]
> True. But `DoubleSummaryStatistics` isn't thread-safe?

Ahh ... to much focus on shortness ;-)

**Comment by gunnarmorling** [comment]
Looking good now. Interestingly, no noticeable difference in terms of execution time: 01:08.811. I reckon the ~400 data points are enough to distribute the aggregation calls enough for the synchronization to not be harmful.

**Pull request merged**
