### PR TITLE
fine tuning performance further

### PR DESCRIPTION
**Pull request by karthikeyan97**
#### Check List:
- [x] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x] Output matches that of `calculate_average_baseline.sh`
- [x] For new entries, or after substantial changes: When implementing custom hash structures, please point to where you deal with hash collisions (line number)

* Execution time:1548ms
* Execution time of reference implementation:208000ms

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Could you rebase this one to latest main and force-push? Thx.

**Comment by karthikeyan97** [comment]
Seems like the test env doesn't have min space I have allocated but this is a valid can u check this @gunnarmorling

**Comment by gunnarmorling** [comment]
Could you adjust the Xms value, please? As discussed before, 20g seems rather excessive, and it should be able to find a setting which makes this run on the CI environment. Thx!

**Comment by karthikeyan97** [comment]
done @gunnarmorling

**Comment by gunnarmorling** [comment]
00:11.352 now.

**Pull request merged**
