### PR TITLE
Improved integer conversion, delayed string creation.

### PR DESCRIPTION
**Pull request by jgrateron**
All test pass
new runtime 14 sec.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Interesting, is this actually faster on your system? On the eval system it's ~19 sec now.

**Comment by jgrateron** [comment]
start my linux in "init 3" defaults the results, now if the time is correct 14 seconds

**Comment by gunnarmorling** [comment]
How is this dealing with hash collisions actually? It seems if two station names yield the same hash code, the aggregation would be wrong?

**Comment by jgrateron** [comment]
I did several tests and there are no collisions between station names, but to prevent this I added the length of the string in the initialization of the hash.

image

**Comment by gunnarmorling** [comment]
Hum, I fail to understand how this resolves the issue. As a matter of principle it must be guaranteed that no values from several stations are mixed up, i.e. all potential collisions must be handled correctly.

**Pull request closed without merging**
