### PR TITLE
Submission #5 [No bitwise tricks nor Unsafe yet; 13th place on leaderboard in local testing using evaluate2.sh]

### PR DESCRIPTION
**Pull request by vemana**
#### Check List:
- [x] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x] Output matches that of `calculate_average_baseline.sh`
- [x] Execution time of reference implementation: 89.5s
- [x] Machine specs: Ryzen 7950X 16 core, 128 GB RAM

9th place on Leaderboard as reported by evaluate2.sh run on the top 10 entries
 
Summary
  vemana: trimmed mean 2.6613015658800006, raw times 2.6672444968800004,2.69366952488,2.62299067588,2.62286704588,2.6966788158800004
  obourgain: trimmed mean 2.7052839972133333, raw times 2.68887464788,2.75071904288,2.6762583008800003,2.6511697608800002,2.77563039188
  spullara: trimmed mean 2.93541452536, raw times 2.91973923336,2.94382176236,2.91269465136,2.94268258036,2.94394135136
  mtopolnik: trimmed mean 1.7677351145066666, raw times 1.76261485184,1.76543366284,1.7751568288400001,1.7537950968400002,1.7997557778400002
  hundredwatt: trimmed mean 2.1452178076733333, raw times 2.13559848534,2.14585098834,2.1535601613399997,2.16198978034,2.1362422733399997
  JamalMulla: trimmed mean 2.40106556698, raw times 2.39724416398,2.41097429098,2.39497824598,2.46275172398,2.38381026398
  artsiomkorzun: trimmed mean 1.6738724361400001, raw times 1.6556292831400001,1.7156163901400001,1.7089712551400003,1.63728812614,1.6570167701400003
  merykitty: trimmed mean 1.9813559809666668, raw times 2.0197908163,1.6982367853,1.9756151293,2.1446047393,1.9486619973
  royvanrijn: trimmed mean 1.46786347914, raw times 1.48326202014,1.44495551314,1.47054033414,1.4525419771399999,1.48050812614
  thomaswue: trimmed mean 1.5627898215866667, raw times 1.58337746192,1.46332770592,1.67277707592,1.63304615892,1.47194584392
  ebarlas: trimmed mean 2.35778699214, raw times 2.33743244714,2.37130350114,2.34715211814,2.4066666951399998,2.35490535714
  isolgpus: trimmed mean 2.8379703537066665, raw times 2.82200337704,2.85542802504,2.82097409804,2.83647965904,3.0591057050400003
  algirdasrascius: trimmed mean 2.7826150059200003, raw times 2.7920901929200004,2.7843075499200003,2.7575244919200004,2.7720028939200003,2.7915345739200004
  jotschi: trimmed mean 3.554084278873333, raw times 3.54855079854,3.57640650954,3.54807588854,3.55923102954,3.5544710085399998

Leaderboard

| # | Result (m:s.ms) | Implementation     | JDK | Submitter     | Notes     |
|---|-----------------|--------------------|-----|---------------|-----------|
| 1 | 00:01.467 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_royvanrijn.java)| 21.0.1-graal | [Roy van Rijn](https://github.com/royvanrijn) | GraalVM native binary |
| 2 | 00:01.562 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_thomaswue.java)| 21.0.1-graal | [Thomas Wuerthinger](https://github.com/thomaswue) | GraalVM native binary |
| 3 | 00:01.673 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_artsiomkorzun.java)| 21.0.1-graal | [Artsiom Korzun](https://github.com/artsiomkorzun) |  |
|   | 00:01.767 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_mtopolnik.java)| 21.0.1-graal | [Marko Topolnik](https://github.com/mtopolnik) |  |
|   | 00:01.981 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_merykitty.java)| 21.0.1-open | [Quan Anh Mai](https://github.com/merykitty) |  |
|   | 00:02.145 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_hundredwatt.java)| 21.0.1-graal | [Jason Nochlin](https://github.com/hundredwatt) |  |
|   | 00:02.357 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_ebarlas.java)| 21.0.1-graal | [Elliot Barlas](https://github.com/ebarlas) |  |
|   | 00:02.401 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_JamalMulla.java)| 21.0.1-graal | [Jamal Mulla](https://github.com/JamalMulla) |  |
|   | 00:02.661 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_vemana.java)| 21.0.1-graal | [Subrahmanyam](https://github.com/vemana) |  |
|   | 00:02.705 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_obourgain.java)| 21.0.1-open | [Olivier Bourgain](https://github.com/obourgain) |  |
|   | 00:02.782 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_algirdasrascius.java)| 21.0.1-open | [Algirdas Ra__ius](https://github.com/algirdasrascius) |  |
|   | 00:02.837 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_isolgpus.java)| 21.0.1-open | [Jamie Stansfield](https://github.com/isolgpus) |  |
|   | 00:02.935 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_spullara.java)| 21.0.1-graal | [Sam Pullara](https://github.com/spullara) |  |
|   | 00:03.554 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_jotschi.java)| 21.0.1-open | [Johannes Sch_th](https://github.com/jotschi) |  |

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@royvanrijn, @artsiomkorzun, @merykitty, in case anyone has input on this one, a look from yours on this one would be appreciated. Thx!

**Comment by vemana** [comment]
Updated with documentation on the approach. Local testing suggests this will be #13 on the leaderboard as of this point.

PS: Not sure I am doing it right with the github branches (github noob). Hope I didn't cause additional work.

**Comment by gunnarmorling** [comment]
Hey, sorry for the delay here. Could you please rebase this to latest main and squash everything into one commit? Thx!

**Comment by gunnarmorling** [comment]
Nevermind, I actually can do that myself. 00:05.530 on the eval machine, very nice. Loving the commenting, too!

**Comment by vemana** [comment]
Thank you! Appreciate the contest and bringing the community together. Well done.

**Pull request merged**
