### PR TITLE
Unsafe

### PR DESCRIPTION
**Pull request by karthikeyan97**
#### Check List:
- [x] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x] Output matches that of `calculate_average_baseline.sh`
- [x] For new entries, or after substantial changes: When implementing custom hash structures, please point to where you deal with hash collisions 354

* Execution time:1607ms
* Execution time of reference implementation:20800ms

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Can you please rebase this to current main, resolve the conflicts, and squash into a single commit? Thx!

**Comment by karthikeyan97** [comment]
> Can you please rebase this to current main, resolve the conflicts, and squash into a single commit? Thx!

done

**Comment by karthikeyan97** [comment]
@gunnarmorling rebased and pushed please test this

**Comment by karthikeyan97** [comment]
@gunnarmorling rebase done please check this

**Pull request closed without merging**
