### PR TITLE
First submission for Reed Thorngag

### PR DESCRIPTION
**Pull request by reedthorngag**
mine: 0m4.909s
base: 3m27.670s

Its pretty bad and unoptimized, I'll try fix it up a bit at some point and optimize it a bit more.

### CODE REVIEW

**Comment by deemkeen** [comment]
something is wrong with the calculations, if you compare them to the reference implementation

**Comment by reedthorngag** [comment]
> Shamelessly sharing this idea for JVM/GC tuning in another PR/discussion? [#15 (comment)](https://github.com/gunnarmorling/1brc/pull/15#issuecomment-1875495420)

That isnt me?

**Comment by reedthorngag** [comment]
ah whoops, I forgot to test it after I "fixed" it lol, mb

**Comment by reedthorngag** [comment]
LOL its not reading the full input file, I'll try work out why and fix it, but it means the time will be a lot higher haha

**Comment by gunnarmorling** [comment]
Hey, I'm gonna close this one as it has been in Draft state for a week and I need to clean the slate a bit. Please feel free to re-open (rebased to current main, passing all the latest tests etc.) once you're ready to submit. Thx!

**Pull request closed without merging**
