### PR TITLE
Basic Implementation with Memory Mapped File, SIMD Search

### PR DESCRIPTION
**Pull request by gamlerhart**
#### Check List:
- [x] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x] Output matches that of `calculate_average_baseline.sh`
* Execution time: 0m49.188s
* Execution time of reference implementation: 3m52.729s

### CODE REVIEW

**Comment by gamlerhart** [comment]
Implementation class: dev.morling.onebrc.CalculateAverage_gamlerhart 

Runtime on my laptop: 50-60 seconds:
6 core/12 hyperthreads: i7-9750H CPU @ 2.60GHz, 32GByte Memory.

Note: Implementation is single threaded at the moment.

**Comment by gamlerhart** [comment]
I'm not sure what the task `All formatting changes by the build are committed` refers to?

**Comment by MeanderingProgrammer** [comment]
> I'm not sure what the task `All formatting changes by the build are committed` refers to?

Hi there, I can help out with this.

When you build this repo with Maven: `./mvnw clean verify` one of the tasks that runs is a formatter, which applies certain rules to your code to make it look consistent. Things like indentation, spacing, and new line rules.

The author just wants you to include these formatting changes in your PR. Which just means make sure you build before submitting.

**Comment by gunnarmorling** [comment]
00:59.901. Nice to see the SIMD stuff. Thx for participating!

**Comment by gamlerhart** [comment]
Well, I also triggered two bug reports ([1](https://mail.openjdk.org/pipermail/panama-dev/2024-January/020214.html), [2](https://mail.openjdk.org/pipermail/panama-dev/2024-January/020208.html)) to the JDK I encountered. And I've learned some stuff. 

There is certainly a lot room for improvement =).

**Pull request merged**
