### PR TITLE
Updates to CalculateAverage_spullara

### PR DESCRIPTION
**Pull request by spullara**
Making another PR to push progress in the open. Inlined a couple of methods so far. Attempts at SIMD acceleration are still failing. Kind of wondering if maybe it is already doing it in the VM for Array.equals for sure.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Instead of re-opening, could you please create a new PR, based on current
upstream/main? Thx!

**Comment by spullara** [comment]
I have SIMD changes in https://github.com/spullara/1brc/tree/simd but they are much slower.

**Comment by gunnarmorling** [comment]
Let me know when you're ready for another run. With 21.0.1-graalce again, I suppose?

**Comment by spullara** [comment]
I don't think enough has changed honestly and I'm not even sure the inlining helps that much. I'll also update to "sdk use" in my script.

**Comment by spullara** [comment]
Should be about 10% faster than before.

**Comment by spullara** [comment]
I've been running it with 21.0.1-graal from sdkman, added it to the script.

**Comment by spullara** [comment]
I have a bug. Don't run it yet! :)

**Comment by yemreinci** [comment]
Hi @spullara, I was able to make the original version perform 25% better on my machine with a few changes. Feel free to use the ideas: https://github.com/gunnarmorling/1brc/pull/86

**Comment by gunnarmorling** [comment]
Hey @spullara, could you rebase this one to latest main and then run this:

```
./test.sh spullara
```

This is a simple test suite I've added to make sure implementations are compliant and there's one failure (I have clarified some value ranges in the course of the day, this may be related). Thanks!

**Comment by spullara** [comment]
Updated and passes. BTW, having test.sh delete my 1B row file that I now need to regenerate is quite the troll :)

**Comment by gunnarmorling** [comment]
> BTW, having test.sh delete my 1B row file that I now need to regenerate is quite the troll :)

Hum, hum, interesting point. I'd consider it volatile data, so 🤷 . The root issue is that we should have made the data set name an argument to the programs under test. Next time.

That said, something seems wrong with this PR now, way too many unrelated changes. Can you rebase/squash so that it only contains your changes over the latest main? Thx!

**Comment by spullara** [comment]
> Hum, hum, interesting point. I'd consider it volatile data, so 🤷 . The root issue is that we should have made the data set name an argument to the programs under test. Next time.

Yeah, mine also takes a file as an argument so I could test locally with a smaller file when it was slower.

**Comment by gunnarmorling** [comment]
Nice, looking good now. 00:12.063, super-clsoe #2 behind @filiphr with 00:12.027!

**Comment by spullara** [comment]
> Nice, looking good now. 00:12.063, super-clsoe #2 behind @filiphr with 00:12.027!

His is using the hash code of the city as a key which is against the rules? Otherwise mine would be even faster.

https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_filiphr.java#L173

**Comment by gunnarmorling** [comment]
Argh, again?! Seems I really need to add a test with 10K distinct keys. It's so easy to miss otherwise. Gnarf.

**Comment by spullara** [comment]
> Argh, again?! Seems I really need to add a test with 10K distinct keys. It's so easy to miss otherwise. Gnarf.

You would have to construct that names that purposefully have the same hash code to discover these bugs with a test. You have to do it by inspection.

**Comment by gunnarmorling** [comment]
Actually, I'm not sure. Seems the key is derived straight from the characters and it is used as a key in a map, not index in an array. I.e. I don't think there could be collisions?

**Comment by spullara** [comment]
If they aren't comparing the actual string value of the keys you can construct keys that collide with their formula. You allow city names up to 100 bytes of UTF-8 and this compresses that to just 4 bytes. It is impossible to construct a 4 byte (int) hash that represents 100 bytes of UTF-8 uniquely.

**Comment by gunnarmorling** [comment]
True. It would just overflow at some point. Gnarf, that stuff is really tough to spot, as I can't generically fabricate colliding values without knowing what's the hash function. @filiphr, I'll remove your entry from the leaderboard for now, until this issue has been fixed. @spullara, thanks for paying attention that closely!

**Comment by filiphr** [comment]
I was reading the discussions around the hashing today. Sorry about it, I didn't have time to adapt it today.

I have an idea similar to also use `Arrays.equals` for this, let's see what that would lead to.

**Pull request merged**
