### PR TITLE
artpar's attempt

### PR DESCRIPTION
**Pull request by artpar**
- parallel execution
- vector for mix/max/sum
- memory mapped files
- cached parsing for numbers

The numbers which I am seeing on my machine

```
[base]                   183.28s user 5.63s system 100% cpu 3:08.77 total
[memory mapped+parallel] 167.33s user 5.04s system 630% cpu 27.321 total
[above+vector]           157.12s user 3.43s system 670% cpu 23.958 total
[update]                 78.74s user  6.10s system 680% cpu 12.459 total
[b7385ed]                65.03s user  5.68s system 664% cpu 10.634 total
[dda0f36]                61.29s user  5.36s system 727% cpu 9.163 total

```

### CODE REVIEW

**Comment by artpar** [comment]
@lobaorn it makes the runtime worse for my implementation.

**Comment by gunnarmorling** [comment]
Could you please run `test.sh artpar` and make sure all the tests pass? Thanks!

**Comment by artpar** [comment]
Done. Thanks for taking the time to organize this @gunnarmorling

**Comment by gunnarmorling** [comment]
00:16.196, nice. Thx for participating!

**Pull request merged**
