### PR TITLE
Add CalculateAverage_ebarlas submission.

### PR DESCRIPTION
**Pull request by ebarlas**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Nice, thanks a lot! Will evaluate it tomorrow. What's the difference
between this one and the baseline on your machine?

**Comment by ebarlas** [comment]
On a `c5.2xlarge` AWS EC2 instance (roughly equivalent to target env):

Reference:
```
real	4m25.991s
user	4m22.901s
sys	0m4.935s
```

Mine:
```
real	0m15.288s
user	1m59.042s
sys	0m0.580s
```

**Comment by gunnarmorling** [comment]
Very cool, looks like a top contender :)

**Comment by ebarlas** [comment]
Thanks! I'm eager to see how it measures up!

I haven't done any micro-optimizations yet. I assume I can simply open subsequent PRs with additional changes?

**Comment by gunnarmorling** [comment]
Yepp, absolutely. You can send follow-up PRs until the challenge closes
(Jan 31).

**Comment by ebarlas** [comment]
Updated exec time after addition optimizations:

```
real	0m10.828s
user	1m24.306s
sys	0m0.660s
```

**Comment by gunnarmorling** [comment]
Hey, could you run `mvn license:format` to add the missing license header, rebase to latest main and force-push to this PR? Thx"!

**Comment by ebarlas** [comment]
Sure, looking now...

**Comment by ebarlas** [comment]
Done. How does that look now?

**Comment by gunnarmorling** [comment]
This looks great! 2nd place right now with 00:16.558 after @spullara! Worth trying how yours fares with GraalVM, too, I suppose.

**Comment by ebarlasgoto** [comment]
@gunnarmorling, silly question: how can I request execution with GraalVM CE? I just re-ran in my test environment and it is indeed noticeably faster there.

I don't see any metadata or env setup indicating GraalVM by @spullara.

**Comment by ebarlas** [comment]
@gunnarmorling, silly question: how can I request execution with GraalVM CE? I just re-ran in my test environment and it is indeed noticeably faster there.
 
 I don't see any metadata or env setup indicating GraalVM by @spullara.

**Comment by gunnarmorling** [comment]
@ebarlas, please specify the JDK in the submission PR (see README). Indeed this wasn't the case for @spullara explicitly, but I read between the lines that this is what he tested with so I interpreted this as to use GraalVM. So just create a new PR for if you'd like to do that. Better yet: could you try whether adding `sdk use java <your distro>` at the beginning of your launch script works? If so, could you create a PR with that and also point that out in the README? Thanks!

Screenshot 2024-01-03 at 17-58-35 Add note about sharing non-Java solutions on GH discussions by rmoff · Pull Request #40 · gunnarmorling_1brc

**Comment by ebarlas** [comment]
Okay, thanks!

**Pull request merged**
