### PR TITLE
Graal Native for SamuelYvon

### PR DESCRIPTION
**Pull request by SamuelYvon**
#### Check List:
- [X] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [X] All formatting changes by the build are committed
- [X] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [X] Output matches that of `calculate_average_baseline.sh`
* Execution time: ~1s
* Execution time of reference implementation: ~2m

I transformed the binary into a native GraalVM binary, based on @royvanrijn's code. Unfortunately, my memory usage is a bit more intense than his and had to enable the GC (although my machine and the test machines are different, so it may have worked remotely).

Thanks to @royvanrijn for making me exploring the AOT side of java!

### CODE REVIEW

**Comment by gunnarmorling** [comment]
I see differences in the output of `./test.sh SamuelYvon` with this one.

**Comment by SamuelYvon** [comment]
Odd since the code has not changed.

Can you provide a bit of the diff?

**Comment by SamuelYvon** [comment]
Never mind I'm a moron, I replaced the forward with a backward slash

**Comment by SamuelYvon** [comment]
@gunnarmorling Sorry for wasting your time, should be back to normal now

**Comment by SamuelYvon** [comment]
@gunnarmorling 

More optimizations added:

- Delayed string (UTF-8) parsing
- Implementation of djb2 for keys
- Vectorized (hopefully?) `equals` fallback

`./tests.sh SamuelYvon` all pass this time ;)

**Comment by gunnarmorling** [comment]
00:12.495 now, i.e. no significant difference.

**Comment by SamuelYvon** [comment]
What! haha damnit

**Comment by SamuelYvon** [comment]
After looking at flamegraphs, I think this is as far I'll get without using unsafe operations. Java's not my language so I'll stop here. Thanks to you @gunnarmorling. You've assembled a piece of Github history here :)

**Comment by gunnarmorling** [comment]
Hehe, awesome, so happy to hear. Thanks for participating!

**Pull request merged**
