### PR TITLE
Trying native-image

### PR DESCRIPTION
**Pull request by artsiomkorzun**
#### Check List:
- [x ] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x ] All formatting changes by the build are committed
- [x ] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x ] Output matches that of `calculate_average_baseline.sh`
* Execution time: Slower than with C2
* Execution time of reference implementation: a lot

@gunnarmorling  please try but do not merge. And could you please post all 5 times. Thank you so much!

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Done. Can you please mark this as a Draft PR until it's ready to go.

```
Benchmark 1: timeout -v 300 ./calculate_average_artsiomkorzun.sh 2>&1
  Time (mean ± σ):      3.833 s ±  0.019 s    [User: 27.582 s, System: 0.694 s]
  Range (min … max):    3.806 s …  3.852 s    5 runs

Summary
  artsiomkorzun: trimmed mean 3.83628959734, raw times 3.8522002303400003,3.8244176803400003,3.8377833493400004,3.84666776234,3.80593837334

Leaderboard

| # | Result (m:s.ms) | Implementation     | JDK | Submitter     | Notes     |
|---|-----------------|--------------------|-----|---------------|-----------|
|   | 00:03.836 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_artsiomkorzun.java)| 21.0.1-graal | [Artsiom Korzun](https://github.com/artsiomkorzun) | GraalVM native binary |

```

**Comment by thomaswue** [comment]
@artsiomkorzun So for you then the Graal JIT version is faster than the AOT version?

**Comment by artsiomkorzun** [comment]
@thomaswue yep, I haven't looked into assembly to find out why.

**Comment by thomaswue** [comment]
The large diff indicates that probably some method is missing inlining. Without PGO, the Graal compiler has to balance the inlining budget and doesn't quite understand how *really important* that one method is. I might try to compile your solution later on my machine to AOT with and without PGO to check.

**Comment by artsiomkorzun** [comment]
That would be really nice! Thank you

**Pull request closed without merging**
