### PR TITLE
initial deemkeen

### PR DESCRIPTION
**Pull request by deemkeen**
Results: 66,44s user 1,30s system 1491% cpu 4,542 total on my Lenovo ThinkPad P15 Gen 2i / 64gb ram

- based on the code provided by @spullara
- synced virtual threads
- Oracle Graal 21 Runtime :  `sdk use java 21-graal`

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Could you please run the following test suite? There seems to be an issue with the calculation:

```
./test.sh deemkeen
```

Once done, please remove the "test failure" label again. Thx!

**Comment by gunnarmorling** [comment]
This seems to hang now for one of the tests:

```
Validating calculate_average_deemkeen.sh -- src/test/resources/samples/measurements-10000-unique-keys.txt
```

**Comment by deemkeen** [comment]
> This seems to hang now for one of the tests:
> 
> ```
> Validating calculate_average_deemkeen.sh -- src/test/resources/samples/measurements-10000-unique-keys.txt
> ```

all tests green! :dancers:

**Comment by gunnarmorling** [comment]
00:14.411, thanks for participating!

**Pull request merged**
