### PR TITLE
More optimizations for ebarlas submission

### PR DESCRIPTION
**Pull request by ebarlas**
#### Check List:
- [x ] Tests pass (`./test.sh ebarlas` shows no differences between expected and actual outputs)
- [ x] All formatting changes by the build are committed
- [ x] Your launch script is named `calculate_average_ebarlas.sh` (make sure to match casing of your GH user name) and is executable
- [x ] Output matches that of `calculate_average_baseline.sh`
* Execution time: 5.9s on `c5.2xlarge` down from 6.8s (13% reduction)
* Execution time of reference implementation: 3m59s

Execution time on CCX33 VM down from 5.7s to 4.7s (18% reduction)

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey, could you rebase this one to latest main, it looks like it's failing the newly added test measurements-shortest. Thx!

**Comment by ebarlas** [comment]
Yes, looking now...

**Comment by ebarlas** [comment]
Hm, that's odd. It works for me. Are you sure there's an issue? I'll look again.

```
$ ./test.sh ebarlas
Validating calculate_average_ebarlas.sh -- src/test/resources/samples/measurements-1.txt
Validating calculate_average_ebarlas.sh -- src/test/resources/samples/measurements-10.txt
Validating calculate_average_ebarlas.sh -- src/test/resources/samples/measurements-10000-unique-keys.txt
Validating calculate_average_ebarlas.sh -- src/test/resources/samples/measurements-2.txt
Validating calculate_average_ebarlas.sh -- src/test/resources/samples/measurements-20.txt
Validating calculate_average_ebarlas.sh -- src/test/resources/samples/measurements-3.txt
Validating calculate_average_ebarlas.sh -- src/test/resources/samples/measurements-boundaries.txt
Validating calculate_average_ebarlas.sh -- src/test/resources/samples/measurements-complex-utf8.txt
Validating calculate_average_ebarlas.sh -- src/test/resources/samples/measurements-dot.txt
Validating calculate_average_ebarlas.sh -- src/test/resources/samples/measurements-short.txt
Validating calculate_average_ebarlas.sh -- src/test/resources/samples/measurements-shortest.txt
```

**Comment by ebarlas** [comment]
I just rebased and force-pushed.

**Comment by gunnarmorling** [comment]
Thx, looking good now.

**Comment by gunnarmorling** [comment]
Nice, this takes it from 00:05.683 down to 00:04.996 on the new evaluation environment.

**Pull request merged**
