### PR TITLE
improve speed, thanks to the following improvements:

### PR DESCRIPTION
**Pull request by yavuztas**
- loop unrolling and eleminating extra calculations
- eleminating instance level variable access
- quicker equals check, checking long by long chunks instead of bytes
- update GraalVM version to the latest

#### Check List:
- [x] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x] Output matches that of `calculate_average_baseline.sh`
- [x] For new entries, or after substantial changes: When implementing custom hash structures, please point to where you deal with hash collisions (lines 175 and 198)

* Execution time: ~2.2s
* Execution time of reference implementation: ~3m.22s

### CODE REVIEW

**Comment by gunnarmorling** [comment]
This one produces incorrect results for the 10K keyset (see create_measurements_3.sh). Could you take a look? Thx!

**Comment by yavuztas** [comment]
Hi @gunnarmorling
There was a bug in the equals method but now it's fixed. Could you please have another look? Many thanks.

**Comment by gunnarmorling** [comment]
It's actually a bit slower than before:

```
Benchmark 1: timeout -v 300 ./calculate_average_yavuztas.sh 2>&1
  Time (mean ± σ):      3.811 s ±  0.089 s    [User: 27.167 s, System: 0.707 s]
  Range (min … max):    3.761 s …  3.970 s    5 runs

Summary
  yavuztas: trimmed mean 3.7753897134400005, raw times 3.78230971344,3.76071144844,3.76312621244,3.97048912444,3.78073321444

Leaderboard

| # | Result (m:s.ms) | Implementation     | JDK | Submitter     | Notes     |
|---|-----------------|--------------------|-----|---------------|-----------|
|   | 00:03.775 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_yavuztas.java)| 21.0.2-graal | [Yavuz Tas](https://github.com/yavuztas) | GraalVM native binary, uses Unsafe |
```

**Comment by yavuztas** [comment]
Hmm, that's strange. Normally, it should be faster. The results I get in my machine compared with top 3:
```
Summary
  royvanrijn: trimmed mean 2.13166147388, raw times 2.1277600158800003,2.14154143188,2.0986444738800003,2.15448226588,2.12568297388
  thomaswue: trimmed mean 2.111515374326667, raw times 2.09593734666,2.1239312216600004,2.1093937626600003,2.11407201366,2.11108034666
  artsiomkorzun: trimmed mean 2.0592471423866665, raw times 2.0852324207199997,2.05694900372,2.05830246172,2.06248996172,2.05160812772
  yavuztas: trimmed mean 2.12233382756, raw times 2.11259103556,2.13310224456,2.14045282756,2.11848041056,2.11541882756

Leaderboard

| # | Result (m:s.ms) | Implementation     | JDK | Submitter     | Notes     |
|---|-----------------|--------------------|-----|---------------|-----------|
| 1 | 00:02.059 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_artsiomkorzun.java)| 21.0.2-graal | [Artsiom Korzun](https://github.com/artsiomkorzun) | GraalVM native binary, uses Unsafe |
| 2 | 00:02.111 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_thomaswue.java)| 21.0.2-graal | [Thomas Wuerthinger](https://github.com/thomaswue) | GraalVM native binary, uses Unsafe |
| 3 | 00:02.122 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_yavuztas.java)| 21.0.2-graal | [Yavuz Tas](https://github.com/yavuztas) | GraalVM native binary, uses Unsafe |
|   | 00:02.131 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_royvanrijn.java)| 21.0.2-graal | [Roy van Rijn](https://github.com/royvanrijn) | GraalVM native binary, uses Unsafe |
```
Is that really the difference for different hardware? I haven't tested on Linux/AMD only on my Mac with m1. @royvanrijn , @thomaswue did you have any similar experience like your solution is much slower on Linux/AMD while it's actually faster on Mac? If so how did you overcome this?

**Comment by gunnarmorling** [comment]
Yes, folks definitely observe different performance characteristics between M1 and the eval machine, due to the different ISAs, e.g. in terms of SIMD register widths. Testing and tuning on a similar hardware is the most promising approach beyond a certain threshold.

**Comment by gunnarmorling** [comment]
Hey @yavuztas, how would you like to proceed here?

**Comment by yavuztas** [comment]
Hi @gunnarmorling, I'm working on a complete rewrite, optimized for the target machine's hardware -- hopefully :)
I will push it soon.

**Comment by yavuztas** [comment]
Hi again @gunnarmorling, I think I'm done with it. I'm out of ideas yet how to improve it more. Hopefully, a better solution. Can you please have a look?

**Comment by gunnarmorling** [comment]
It's faster for the standard keyset indeed, but it doesn't produce any output at all for the 10K key set :(

**Comment by yavuztas** [comment]
Really? It works for 10K on me and the output also perfectly matches. Any errors or it just hangs?

**Comment by gunnarmorling** [comment]
No errors, just no output whatsoever. When I run it in JVM mode, the output indeed is correct. But I have no idea how to approach that native issue, unfortunately.

**Comment by yavuztas** [comment]
Sorry, accidentally pushed it to the main branch :(
I will revert the last two commits

**Comment by gunnarmorling** [comment]
Yepp, looking good now, also passing with 10K keys.

```
Benchmark 1: timeout -v 300 ./calculate_average_yavuztas.sh 2>&1
  Time (mean ± σ):      2.328 s ±  0.050 s    [User: 0.003 s, System: 0.003 s]
  Range (min … max):    2.277 s …  2.407 s    5 runs

Summary
  yavuztas: trimmed mean 2.31906419842, raw times 2.3034457774200003,2.27678964042,2.30782189442,2.40697815042,2.34592492342

Leaderboard

| # | Result (m:s.ms) | Implementation     | JDK | Submitter     | Notes     |
|---|-----------------|--------------------|-----|---------------|-----------|
|   | 00:02.319 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_yavuztas.java)| 21.0.2-graal | [Yavuz Tas](https://github.com/yavuztas) | GraalVM native binary, uses Unsafe |
```

**Comment by gunnarmorling** [comment]
Hey @yavuztas!

Congrats again on being in the Top 20 of the One Billion Row Challenge!

To celebrate this amazing achievement, I would like to send you a 1BRC t-shirt and coffee mug. To claim your prize, fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLScQLlJiI0KU8rMgoWaNAyKNO_O2Ndmjq9qnv_vmNq6rpL87LA/viewform) by Feb 18. **After** submitting the form, please provide a comment with the random value you've specified in the form, so that I know it is you who submitted it.

All data entered will solely be used in relation to processing this shipment. Shipments can be sent to any country listed [here](https://help.spreadshirt.com/hc/de/articles/207165489-Lieferzeit-Versandkosten?locale=de_DE) or [here](https://help.spreadshirt.com/hc/en-us/articles/207165489-Shipping-Times-and-Costs) (I'll use whichever one is cheaper for me to ship to your location). A big thank you to [Decodable](https://www.decodable.co/) for sponsoring these prizes!

Thanks a lot for participating in 1BRC,

--Gunnar

**Comment by yavuztas** [comment]
Hi @gunnarmorling 
Thanks for the prizes, and also to Decodable for sponsoring.
Here is the secret: 23049 31739

**Pull request merged**
