### PR TITLE
Second attempt with various improvements

### PR DESCRIPTION
**Pull request by JamalMulla**
#### Check List:
- [x] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x] Output matches that of `calculate_average_baseline.sh`
- [x] For new entries, or after substantial changes: When implementing custom hash structures, please point to where you deal with hash collisions (line number)

* Execution time: 3s
* Execution time of reference implementation: 4m

Shaved off around 1.5s from my initial submission. Also trying with graal native binary as it seems to give slightly better results and all the top entries are also using it.

Most of the changes are just reducing function calls, inlining the hashing, etc

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Seeing a test failure now:

```
+ timeout -v 300 ./test.sh JamalMulla

Using java version 21.0.1-graal in this shell.
Validating calculate_average_JamalMulla.sh -- src/test/resources/samples/measurements-10000-unique-keys.txt
Validating calculate_average_JamalMulla.sh -- src/test/resources/samples/measurements-10.txt
Validating calculate_average_JamalMulla.sh -- src/test/resources/samples/measurements-1.txt
Validating calculate_average_JamalMulla.sh -- src/test/resources/samples/measurements-20.txt
Validating calculate_average_JamalMulla.sh -- src/test/resources/samples/measurements-2.txt
Validating calculate_average_JamalMulla.sh -- src/test/resources/samples/measurements-3.txt
Validating calculate_average_JamalMulla.sh -- src/test/resources/samples/measurements-boundaries.txt
Validating calculate_average_JamalMulla.sh -- src/test/resources/samples/measurements-complex-utf8.txt
1c1
< ;118.9;118.9;118.9
---
> B;8.9;8.9;8.9

FAILURE: ./test.sh JamalMulla failed
```

**Comment by JamalMulla** [comment]
@gunnarmorling Been fixed now.

**Review by gunnarmorling — COMMENTED** [review]
This is not passing tests now:

```
Validating calculate_average_JamalMulla.sh -- src/test/resources/samples/measurements-10000-unique-keys.txt
2325a2326,2331
> id3090;1.0;1.0;1.0
> id3091;1.0;1.0;1.0
> id3092;1.0;1.0;1.0
> id3093;1.0;1.0;1.0
> id3094;1.0;1.0;1.0
> id3095;1.0;1.0;1.0
3430a3437,3442
> id4090;1.0;1.0;1.0
> id4091;1.0;1.0;1.0
> id4092;1.0;1.0;1.0
> id4093;1.0;1.0;1.0
> id4094;1.0;1.0;1.0
> id4095;1.0;1.0;1.0
7868a7881,7886
> id8090;1.0;1.0;1.0
> id8091;1.0;1.0;1.0
> id8092;1.0;1.0;1.0
> id8093;1.0;1.0;1.0
> id8094;1.0;1.0;1.0
> id8095;1.0;1.0;1.0
8973a8992,8993
> id9090;1.0;1.0;1.0
> id9091;1.0;1.0;1.0

FAILURE: ./test.sh JamalMulla failed
```

Also, where are you dealing with hash collisions?

**Comment by JamalMulla** [comment]
> This is not passing tests now:
> 
> ```
> Validating calculate_average_JamalMulla.sh -- src/test/resources/samples/measurements-10000-unique-keys.txt
> 2325a2326,2331
> > id3090;1.0;1.0;1.0
> > id3091;1.0;1.0;1.0
> > id3092;1.0;1.0;1.0
> > id3093;1.0;1.0;1.0
> > id3094;1.0;1.0;1.0
> > id3095;1.0;1.0;1.0
> 3430a3437,3442
> > id4090;1.0;1.0;1.0
> > id4091;1.0;1.0;1.0
> > id4092;1.0;1.0;1.0
> > id4093;1.0;1.0;1.0
> > id4094;1.0;1.0;1.0
> > id4095;1.0;1.0;1.0
> 7868a7881,7886
> > id8090;1.0;1.0;1.0
> > id8091;1.0;1.0;1.0
> > id8092;1.0;1.0;1.0
> > id8093;1.0;1.0;1.0
> > id8094;1.0;1.0;1.0
> > id8095;1.0;1.0;1.0
> 8973a8992,8993
> > id9090;1.0;1.0;1.0
> > id9091;1.0;1.0;1.0
> 
> FAILURE: ./test.sh JamalMulla failed
> ```
> 
> Also, where are you dealing with hash collisions?

Very confusing cause it passes locally. What does that output mean? 8973a8992?

And [here](https://github.com/gunnarmorling/1brc/pull/510/files#diff-93b51c6a85afa4ea9f5165bc26b68f128d4cc71cb062c7d2c25c70cac50475b8R190-R193) is where I'm handling collisions

**Comment by JamalMulla** [comment]
I also don't understand why the Github build doesn't report test failures? seems like an obvious build step

**Comment by gunnarmorling** [comment]
Here's the original PR: https://github.com/gunnarmorling/1brc/pull/106. Any help for driving it over the finishing line will be more than welcome :)

**Comment by gunnarmorling** [comment]
Moved ahead actually, tests run on CI now. So could you please rebase this to current main and force-push, and it will trigger the tests. Thx.

**Comment by gunnarmorling** [comment]
> Very confusing cause it passes locally. What does that output mean? 8973a8992?

It means that there are rows missing in the output. Seems something is wrong with creating the chunks, there's always six rows missing from each one:

```
Validating calculate_average_JamalMulla.sh -- src/test/resources/samples/measurements-10000-unique-keys.txt
1214a1215,1220
> id2090;1.0;1.0;1.0
> id2091;1.0;1.0;1.0
> id2092;1.0;1.0;1.0
> id2093;1.0;1.0;1.0
> id2094;1.0;1.0;1.0
> id2095;1.0;1.0;1.0
2319a2326,2331
> id3090;1.0;1.0;1.0
> id3091;1.0;1.0;1.0
> id3092;1.0;1.0;1.0
> id3093;1.0;1.0;1.0
> id3094;1.0;1.0;1.0
> id3095;1.0;1.0;1.0
3424a3437,3442
> id4090;1.0;1.0;1.0
> id4091;1.0;1.0;1.0
> id4092;1.0;1.0;1.0
> id4093;1.0;1.0;1.0
> id4094;1.0;1.0;1.0
> id4095;1.0;1.0;1.0
5640a5659,5664
> id6090;1.0;1.0;1.0
> id6091;1.0;1.0;1.0
> id6092;1.0;1.0;1.0
> id6093;1.0;1.0;1.0
> id6094;1.0;1.0;1.0
> id6095;1.0;1.0;1.0
6745a6770,6775
> id7090;1.0;1.0;1.0
> id7091;1.0;1.0;1.0
> id7092;1.0;1.0;1.0
> id7093;1.0;1.0;1.0
> id7094;1.0;1.0;1.0
> id7095;1.0;1.0;1.0
7850a7881,7886
> id8090;1.0;1.0;1.0
> id8091;1.0;1.0;1.0
> id8092;1.0;1.0;1.0
> id8093;1.0;1.0;1.0
> id8094;1.0;1.0;1.0
> id8095;1.0;1.0;1.0
8955a8992,8997
> id9090;1.0;1.0;1.0
> id9091;1.0;1.0;1.0
> id9092;1.0;1.0;1.0
> id9093;1.0;1.0;1.0
> id9094;1.0;1.0;1.0
> id9095;1.0;1.0;1.0
```

**Comment by JamalMulla** [comment]
> Moved ahead actually, tests run on CI now. So could you please rebase this to current main and force-push, and it will trigger the tests. Thx.

Nice, this is awesome. Hopefully a lot less friction. I see my fixes have finally passed the tests.

**Comment by gunnarmorling** [comment]
Tests look good now, but it takes unduly long for the 10K keyset (see _create_measurements_3.sh_). Could you take a look, I am running the top 15 entries against that keyset, and as yours is up there, it would be nice if it could handle it. Thx.

**Comment by JamalMulla** [comment]
> Tests look good now, but it takes unduly long for the 10K keyset (see _create_measurements_3.sh_). Could you take a look, I am running the top 15 entries against that keyset, and as yours is up there, it would be nice if it could handle it. Thx.

Hmm I can't reproduce this behaviour at all. i ran create_measurements3.sh with 1billion and I get this

```
 Performance counter stats for './calculate_average_JamalMulla.sh':

         34,723.19 msec task-clock                #    6.696 CPUs utilized          
             6,147      context-switches          #  177.029 /sec                   
                 7      cpu-migrations            #    0.202 /sec                   
           270,316      page-faults               #    7.785 K/sec                  
   <not supported>      cycles                                                      
   <not supported>      instructions                                                
   <not supported>      branches                                                    
   <not supported>      branch-misses                                               

       5.185930430 seconds time elapsed

      33.162106000 seconds user
       1.400924000 seconds sys
```
Is there something else you did for the test?

**Comment by JamalMulla** [comment]
@gunnarmorling any ideas? i would really like to get this evaluated. If you can provide more details i'll try to fix but i can't even reproduce it as is

**Comment by tivrfoa** [comment]
> @gunnarmorling any ideas? i would really like to get this evaluated. If you can provide more details i'll try to fix but i can't even reproduce it as is

Try to create other datasets from the 10k (each time it generates a new one), and compare the output with some valid solution.

Maybe deadlock or can't find a key?

**Comment by JamalMulla** [comment]
> > @gunnarmorling any ideas? i would really like to get this evaluated. If you can provide more details i'll try to fix but i can't even reproduce it as is
> 
> Try to create other datasets from the 10k (each time it generates a new one), and compare the output with some valid solution.
> 
> Maybe deadlock or can't find a key?

yeah been trying this. no luck so far. also annoying cause it takes a while to generate 1bil each time

**Comment by tivrfoa** [comment]
> > > @gunnarmorling any ideas? i would really like to get this evaluated. If you can provide more details i'll try to fix but i can't even reproduce it as is
> > 
> > 
> > Try to create other datasets from the 10k (each time it generates a new one), and compare the output with some valid solution.
> > Maybe deadlock or can't find a key?
> 
> yeah been trying this. no luck so far. also annoying cause it takes a while to generate 1bil each time

Try 100 and 200 million rows. It's faster to generate

**Comment by tivrfoa** [comment]
> > > @gunnarmorling any ideas? i would really like to get this evaluated. If you can provide more details i'll try to fix but i can't even reproduce it as is
> > 
> > 
> > Try to create other datasets from the 10k (each time it generates a new one), and compare the output with some valid solution.
> > Maybe deadlock or can't find a key?
> 
> yeah been trying this. no luck so far. also annoying cause it takes a while to generate 1bil each time

Try these. Ask permission for these files:

https://drive.google.com/file/d/1sVA0yUuo5oZoeAQFoPJgaF0cQnq4fPCr/view?usp=sharing

https://drive.google.com/file/d/1hB72HaFC87Pjykv1mu0CIF4kXO5Qjefs/view?usp=sharing

**Comment by gunnarmorling** [comment]
Getting this error:

```
Fatal error: Failed to leave the current IsolateThread context and to detach the current thread. (code 12)
```

I have seen it with another native image entry, but I don't know what the cause is. @thomaswue might have an idea.

**Comment by JamalMulla** [comment]
@gunnarmorling I've removed one of the native build options which may have played a part in the error (not sure though). Could you re-test please. No idea what else to try and would like to see the time for the normal 1brc at least. Thanks!

**Comment by tivrfoa** [comment]
> Getting this error:
> 
> ```
> Fatal error: Failed to leave the current IsolateThread context and to detach the current thread. (code 12)
> ```
> 
> I have seen it with another native image entry, but I don't know what the cause is. @thomaswue might have an idea.

Do you remember the other code that had the same error?

Maybe there's something similar in their solutions.

Another thing that could have been tried was to use same native flags of one solution that is working.
Also use newest graal version: `sdk use java 21.0.2-graal 1>&2`

And what makes the bug more interesting, is that @JamalMulla said it was working in his computer. =)

**Comment by gunnarmorling** [comment]
So the isolate error seems to be intermittent, can't reproduce it any longer (also without your latest change). So the remainging issue is that it still doesn't produce the correct output for the 10K key set test:

```
+ timeout -v 300 ./test.sh JamalMulla measurements_10K_1B.txt

Using java version 21.0.1-graal in this shell.
Validating calculate_average_JamalMulla.sh -- measurements_10K_1B.txt
6482c6482
< noA;-19.7;8.2;39.3
---
> noA;-23.2;8.2;39.3
6492c6492
< noWuhuNanningHar;-23.2;10.4;41.6
---
> noWuhuNanningHar;-19.0;11.6;41.6

FAILURE: ./test.sh JamalMulla measurements_10K_1B.txt failed
```

**Comment by JamalMulla** [comment]
@gunnarmorling fixed 🤞!

**Comment by gunnarmorling** [comment]
Same diff for the 10K key set test as before :(

**Comment by JamalMulla** [comment]
> Same diff for the 10K key set test as before :(

@gunnarmorling last attempt before i give up. please recheck

**Comment by JamalMulla** [comment]
> Yepp, looking good now.
> 
> ```
> Benchmark 1: timeout -v 300 ./calculate_average_JamalMulla.sh 2>&1
>   Time (mean ± σ):      3.124 s ±  0.073 s    [User: 21.819 s, System: 0.702 s]
>   Range (min … max):    3.079 s …  3.252 s    5 runs
> 
> Summary
>   JamalMulla: trimmed mean 3.0958672756066665, raw times 3.07938657994,3.09427596894,3.1120593309399998,3.08126652694,3.25184166094
> 
> Leaderboard
> 
> | # | Result (m:s.ms) | Implementation     | JDK | Submitter     | Notes     |
> |---|-----------------|--------------------|-----|---------------|-----------|
> |   | 00:03.095 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_JamalMulla.java)| 21.0.2-graal | [Jamal Mulla](https://github.com/JamalMulla) | GraalVM native binary, uses Unsafe |
> ```

Finally 🎉

**Comment by gunnarmorling** [comment]
Hey @JamalMulla!

Congrats again on being in the Top 20 of the One Billion Row Challenge!

To celebrate this amazing achievement, I would like to send you a 1BRC t-shirt and coffee mug. To claim your prize, fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLScQLlJiI0KU8rMgoWaNAyKNO_O2Ndmjq9qnv_vmNq6rpL87LA/viewform) by Feb 18. **After** submitting the form, please provide a comment with the random value you've specified in the form, so that I know it is you who submitted it.

All data entered will solely be used in relation to processing this shipment. Shipments can be sent to any country listed [here](https://help.spreadshirt.com/hc/de/articles/207165489-Lieferzeit-Versandkosten?locale=de_DE) or [here](https://help.spreadshirt.com/hc/en-us/articles/207165489-Shipping-Times-and-Costs) (I'll use whichever one is cheaper for me to ship to your location). A big thank you to [Decodable](https://www.decodable.co/) for sponsoring these prizes!

Thanks a lot for participating in 1BRC,

--Gunnar

**Comment by JamalMulla** [comment]
> Hey @JamalMulla!
> 
> Congrats again on being in the Top 20 of the One Billion Row Challenge!
> 
> To celebrate this amazing achievement, I would like to send you a 1BRC t-shirt and coffee mug. To claim your prize, fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLScQLlJiI0KU8rMgoWaNAyKNO_O2Ndmjq9qnv_vmNq6rpL87LA/viewform) by Feb 18. **After** submitting the form, please provide a comment with the random value you've specified in the form, so that I know it is you who submitted it.
> 
> All data entered will solely be used in relation to processing this shipment. Shipments can be sent to any country listed [here](https://help.spreadshirt.com/hc/de/articles/207165489-Lieferzeit-Versandkosten?locale=de_DE) or [here](https://help.spreadshirt.com/hc/en-us/articles/207165489-Shipping-Times-and-Costs) (I'll use whichever one is cheaper for me to ship to your location). A big thank you to [Decodable](https://www.decodable.co/) for sponsoring these prizes!
> 
> Thanks a lot for participating in 1BRC,
> 
> --Gunnar

Hey, I've filled in the form. My numbers were 21975 11916. Thanks

**Pull request merged**
