### PR TITLE
Add CalculateAverage_moysesb

### PR DESCRIPTION
**Pull request by moysesb**
Yet another mmap based implementation. My implementation cannot compete with the ones using open hash arrays, but I'm curious to see how it does in the target machine.

My system has a i7-8750H CPU (6 cores ,12 "threads") and 16GB RAM. My implementation finishes in ~22s, while the reference implementation finishes in ~3.2min.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Could you please take a look at the test failures reported by

```
./test.sh moysesb
```

And remove the "test failure" label once done? Thx!

**Comment by moysesb** [comment]
Oops, sorry, should have run the tests yesterday before pushing.

**Comment by moysesb** [comment]
About the test failure label, I don't think I have write access to labels in this repo.

**Comment by gunnarmorling** [comment]
> Oops, sorry, should have run the tests yesterday before pushing.

No worries, just added this earlier today to cover some corner cases (should have done so from the beginning).

**Comment by gunnarmorling** [comment]
@moysesb, something still is wrong, the output differs from that of the reference implementation (min/max values). Could you take a look?

**Comment by moysesb** [comment]
What's the procedure for checking the calculated values? I generated a couple of measurement inputs locally with create_measurements.sh (from 1_000 to 10_000_000 lines) and the results are always the same between my class and the baseline.

**Comment by gunnarmorling** [comment]
Can you try and create one with 1B rows actually? If I'd have to guess, I'd
say there's some value overflow somewhere.

**Comment by moysesb** [comment]
Yeah, that was it. Last chunk was being truncated because I can't do basic arithmetic :/

Fixed (I hope).

**Comment by gunnarmorling** [comment]
00:32.764 Nice!

**Pull request merged**
