### PR TITLE
Run ebarlas solution with GraalVM CE 21.0.1

### PR DESCRIPTION
**Pull request by ebarlas**
This PR is a request to run the ebarlas solution with GraalVM CE 21.0.1.

The ebarlas shell script has been updated.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Will do. Can you add a note on this to the README, too? Thx!

**Comment by ebarlasgoto** [comment]
Sure, an FAQ note or something in Entering the Challange?

**Comment by gunnarmorling** [comment]
> Sure, an FAQ note or something in Entering the Challange?

Dealer's choice :)

**Comment by ebarlas** [comment]
Done. Hope it looks okay! I'm editing from my phone directly on GH - a unique challenge!

**Pull request merged**
