### PR TITLE
adopt @spullara's double parsing code

### PR DESCRIPTION
**Pull request by richardstartin**
Adapts the double parsing code from @spullara's submission - now runs in ~9s locally

### CODE REVIEW

**Comment by richardstartin** [comment]
Also increases chunk size

**Comment by richardstartin** [comment]
I think I'm done tweaking this, I'll probably adopt another algorithm if I make more changes. Very curious to see how this fares in the evaluation environment though :)

**Comment by gunnarmorling** [comment]
@richardstartin, could you run `mvn clean verify` and append the resulting formatting changes to this PR? Thx!

**Comment by gunnarmorling** [comment]
00:23.260 now. Merging, I'll take care of the formatting.

**Comment by richardstartin** [comment]
Sorry my bad on the formatting, thanks for running again.

**Pull request merged**
