### PR TITLE
mtopolnik submission 3

### PR DESCRIPTION
**Pull request by mtopolnik**
#### Check List:

- [x] You have run `./mvnw verify` and the project builds successfully
- [x] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x] Output matches that of `calculate_average_baseline.sh`
- [x] For new entries, or after substantial changes: When implementing custom hash structures, please point to where you deal with hash collisions: line 378

* Execution time: 2.5 s
* Execution time of reference implementation: minutes

This refreshes my solution after two weeks of inactivity. Hopefully it gets me closer to my Hazelcast Gang!

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Nice:

```
Benchmark 1: timeout -v 300 ./calculate_average_mtopolnik.sh 2>&1
  Time (mean ± σ):      2.315 s ±  0.057 s    [User: 0.002 s, System: 0.006 s]
  Range (min … max):    2.218 s …  2.359 s    5 runs

Summary
  mtopolnik: trimmed mean 2.332358688833333, raw times 2.2177691565,2.3432480145000003,2.3137745535,2.3400534985,2.3594586395

Leaderboard

| # | Result (m:s.ms) | Implementation     | JDK | Submitter     | Notes     |
|---|-----------------|--------------------|-----|---------------|-----------|
|   | 00:02.332 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_mtopolnik.java)| 21.0.2-graal | [Marko Topolnik](https://github.com/mtopolnik) | GraalVM native binary, uses Unsafe |
```

**Comment by gunnarmorling** [comment]
Hey @mtopolnik!

Congrats again on being in the Top 20 of the One Billion Row Challenge!

To celebrate this amazing achievement, I would like to send you a 1BRC t-shirt and coffee mug. To claim your prize, fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLScQLlJiI0KU8rMgoWaNAyKNO_O2Ndmjq9qnv_vmNq6rpL87LA/viewform) by Feb 18. **After** submitting the form, please provide a comment with the random value you've specified in the form, so that I know it is you who submitted it.

All data entered will solely be used in relation to processing this shipment. Shipments can be sent to any country listed [here](https://help.spreadshirt.com/hc/de/articles/207165489-Lieferzeit-Versandkosten?locale=de_DE) or [here](https://help.spreadshirt.com/hc/en-us/articles/207165489-Shipping-Times-and-Costs) (I'll use whichever one is cheaper for me to ship to your location). A big thank you to [Decodable](https://www.decodable.co/) for sponsoring these prizes!

Thanks a lot for participating in 1BRC,

--Gunnar

**Comment by mtopolnik** [comment]
19307 29280

**Comment by mtopolnik** [comment]
Sorry for the confusion, I filled out the wrong form as well?

**Comment by gunnarmorling** [comment]
No worries at all. Yeah, if you could fill out the form linked from this PR, that would be great. Thx!

**Pull request merged**
