### PR TITLE
Improved artsiomkorzun solution

### PR DESCRIPTION
**Pull request by artsiomkorzun**
Improvements:
* Use parsing idea from royvanrijn and merykitty
* Use Unsafe for parsing
* Use Unsafe for aggregation

### CODE REVIEW

**Comment by gunnarmorling** [comment]
This fails tests due to additional, unexpected outputs. Also needs a `--enable-preview` in the launch script.

**Comment by artsiomkorzun** [comment]
Epsilon gc outputs two lines in stdout. That's why the tests fail. Fixed by using serial gc for now.

**Comment by gunnarmorling** [comment]
@artsiomkorzun, still seeing a test failure. Have you run `./test.sh artsiomkorzun`?

**Comment by artsiomkorzun** [comment]
@gunnarmorling It passes locally. Can you please attach a screenshot?
Screenshot 2024-01-10 at 22 13 20

**Comment by gunnarmorling** [comment]
That's what I get:

```
Validating calculate_average_artsiomkorzun.sh -- src/test/resources/samples/measurements-10000-unique-keys.txt
Validating calculate_average_artsiomkorzun.sh -- src/test/resources/samples/measurements-10.txt
Validating calculate_average_artsiomkorzun.sh -- src/test/resources/samples/measurements-1.txt
Validating calculate_average_artsiomkorzun.sh -- src/test/resources/samples/measurements-20.txt
Validating calculate_average_artsiomkorzun.sh -- src/test/resources/samples/measurements-2.txt
Validating calculate_average_artsiomkorzun.sh -- src/test/resources/samples/measurements-3.txt
Validating calculate_average_artsiomkorzun.sh -- src/test/resources/samples/measurements-boundaries.txt
Validating calculate_average_artsiomkorzun.sh -- src/test/resources/samples/measurements-complex-utf8.txt
Validating calculate_average_artsiomkorzun.sh -- src/test/resources/samples/measurements-dot.txt
1c1
< {-=1.0/1.0/1.0, .=1.0/1.0/1.0}
---
> {-=1.0/1.5/2.0, .=1.0/1.0/1.0}
```

**Comment by gunnarmorling** [comment]
Can you reproduce it?

**Comment by artsiomkorzun** [comment]
@gunnarmorling Yep, fixed. Please try one more time :)

**Comment by gunnarmorling** [comment]
All passing now. From 00:06.338 down to 00:03.796 on the new eval machine. Nice!

**Pull request merged**
