### PR TITLE
Add davecom Entry

### PR DESCRIPTION
**Pull request by davecom**
My main class is `CalculateAverage_davecom`

My implementation uses memory mapped files and runs between 19 and 24 seconds on my M1 MacBook Air (8 cores) with 16 GB of RAM.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thanks for participating! Could you please run `./test.sh davecom` and verify that there are no test failures before we evaluate (it's gonna be part of the CI build eventually)? Thx!

**Comment by davecom** [comment]
Yes, I did run it before submitting, @gunnarmorling. Thanks!

**Comment by gunnarmorling** [comment]
00:24.879. Thanks for participating!

**Comment by davecom** [comment]
Thanks for creating the contest!

**Pull request merged**
