### PR TITLE
Adding Johannes Schüth's submission

### PR DESCRIPTION
**Pull request by Jotschi**
Class: dev.morling.onebrc.CalculateAverage_jotschi

Description: Modified spullar implementation which makes use of JEP 424 / Foreign Function & Memory API and reduces usage of ByteBuffer and byte arrays.  

Execution time: real    0m10.116s
CPU: Core i7 - 7700k, 8 Cores
Mem: 64GB

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Could you please take a look at the test failures reported by

```
./test.sh jotschi
```

And remove the "test failure" label once done? Thx!

**Comment by Jotschi** [comment]
@gunnarmorling I have fixed the issues and rebased my PR but I don't seem to have permission to remove the github label from PR.

**Comment by gunnarmorling** [comment]
Hum, still seeing a test failure:

```
Validating calculate_average_jotschi.sh -- src/test/resources/samples/measurements-10000-unique-keys.txt

real	0m0.247s
user	0m0.966s
sys	0m0.082s
Validating calculate_average_jotschi.sh -- src/test/resources/samples/measurements-10.txt

real	0m0.162s
user	0m0.500s
sys	0m0.059s
Validating calculate_average_jotschi.sh -- src/test/resources/samples/measurements-1.txt

real	0m0.174s
user	0m0.497s
sys	0m0.059s
1c1
< {Kunming=19.8/19.8/19.8, g=19.8/19.8/19.8, ing=19.8/19.8/19.8, ming=19.8/19.8/19.8, ng=19.8/19.8/19.8, nming=19.8/19.8/19.8, unming=19.8/19.8/19.8}
---
> {Kunming=19.8/19.8/19.8}
```

**Comment by Jotschi** [comment]
Strange - It did not give me a diff. I'll re-check.

**Comment by Jotschi** [comment]
@gunnarmorling  Woops - I pushed in wrong branch. Now the changes to my impl. are updated. Sorry for the mistake. I hope you can still keep up with the influx of PR's :)

**Comment by gunnarmorling** [comment]
00:13.430, nice! Thx for participating!

**Pull request merged**
