### PR TITLE
Update seijikun implementation

### PR DESCRIPTION
**Pull request by seijikun**
Updated with
- SIMD for station name parsing
- Fewer String allocations
- Moved from double to integer maths

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey, could you please rebase this one and also make sure all the tests pass (added those today to cover some corner cases):

```
./test.sh seijikun
```

Thx!

**Comment by seijikun** [comment]
> Hey, could you please rebase this one and also make sure all the tests pass (added those today to cover some corner cases):
> 
> ```
> ./test.sh seijikun
> ```
> 
> Thx!

Okay, done! Tests seem to succeed

**Comment by seijikun** [comment]
Whoops, sorry! You're right.
The bug depended on the amount of cores in the test machine. I rewrote the chunking logic to now be hopefully much more robust.

**Comment by gunnarmorling** [comment]
00:22.709 now, thx for participating!

**Pull request merged**
