### PR TITLE
dalogax solution - CalculateAverage_dalogax

### PR DESCRIPTION
**Pull request by dalogax**
#### Check List:
- [X] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [X All formatting changes by the build are committed
- [X] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [X] Output matches that of `calculate_average_baseline.sh`
* Execution time: 1,04s
* Execution time of reference implementation: 3m

I used a Ryzen 5 3600X with 6 cores / 12 threads and 32 Gb of Ram. On a Windows installation using WSL (I topped WSL to 8 vCores so I can match your setup)

Thank you for such a great challenge! I had fun 🥳

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey, I'm seeing some test differences:

```
Validating calculate_average_dalogax.sh -- src/test/resources/samples/measurements-20.txt

real	0m0.098s
user	0m0.100s
sys	0m0.034s
1c1
< {Abéché1️⃣🐝🏎️=27.3/27.3/27.3, Almaty1️⃣🐝🏎️=15.3/15.3/15.3, Baghdad1️⃣🐝🏎️=26.0/26.0/26.0, Bangkok1️⃣🐝🏎️=25.6/25.6/25.6, Berlin1️⃣🐝🏎️=-0.3/-0.3/0.0, Birao1️⃣🐝🏎️=33.5/33.5/33.5, Canberra1️⃣🐝🏎️=5.2/5.2/5.2, Chittagong1️⃣🐝🏎️=12.6/12.6/12.6, Da Nang1️⃣🐝🏎️=33.7/33.7/33.7, Edinburgh1️⃣🐝🏎️=19.8/19.8/19.8, Irkutsk1️⃣🐝🏎️=9.9/9.9/9.9, Lhasa1️⃣🐝🏎️=13.4/13.4/13.4, Lyon1️⃣🐝🏎️=1.8/1.8/1.8, Mogadishu1️⃣🐝🏎️=11.5/11.5/11.5, Nashville1️⃣🐝🏎️=-4.9/-4.9/0.0, Odesa1️⃣🐝🏎️=6.5/6.5/6.5, Parakou1️⃣🐝🏎️=36.3/36.3/36.3, Tamanrasset1️⃣🐝🏎️=17.9/17.9/17.9, Tirana1️⃣🐝🏎️=27.7/27.7/27.7, Xi'an1️⃣🐝🏎️=17.5/17.5/17.5}
---
> {Abéché1️⃣🐝🏎️=27.3/27.3/27.3, Almaty1️⃣🐝🏎️=15.3/15.3/15.3, Baghdad1️⃣🐝🏎️=26.0/26.0/26.0, Bangkok1️⃣🐝🏎️=25.6/25.6/25.6, Berlin1️⃣🐝🏎️=-0.3/-0.3/-0.3, Birao1️⃣🐝🏎️=33.5/33.5/33.5, Canberra1️⃣🐝🏎️=5.2/5.2/5.2, Chittagong1️⃣🐝🏎️=12.6/12.6/12.6, Da Nang1️⃣🐝🏎️=33.7/33.7/33.7, Edinburgh1️⃣🐝🏎️=19.8/19.8/19.8, Irkutsk1️⃣🐝🏎️=9.9/9.9/9.9, Lhasa1️⃣🐝🏎️=13.4/13.4/13.4, Lyon1️⃣🐝🏎️=1.8/1.8/1.8, Mogadishu1️⃣🐝🏎️=11.5/11.5/11.5, Nashville1️⃣🐝🏎️=-4.9/-4.9/-4.9, Odesa1️⃣🐝🏎️=6.5/6.5/6.5, Parakou1️⃣🐝🏎️=36.3/36.3/36.3, Tamanrasset1️⃣🐝🏎️=17.9/17.9/17.9, Tirana1️⃣🐝🏎️=27.7/27.7/27.7, Xi'an1️⃣🐝🏎️=17.5/17.5/17.5}
```

**Comment by dalogax** [comment]
I am so sorry, indeed there was a bug when the max value was negative (initialitation was zero). 1000 apologies for the inconvenience and again thank you for such a fun challenge. I hope you can review the submission again.

**Comment by gunnarmorling** [comment]
Hum, hum, does this complete on the 1B rowset? It hangs for me when trying that.

**Comment by gunnarmorling** [comment]
Gonna close this for now as I haven't heard back and I need to clean the slate a bit. Please feel free to re-open once you're positive all tests pass and it does finish on a 1B rows dataset (please rebase to current main before doing so). Thx!

**Comment by dalogax** [comment]
Ok, don't worry. It workes on my PC :D I synced my fork and generated a new file. I'm not in the top so no worry for my submission. I had fun, thank you again.

**Comment by gunnarmorling** [comment]
Awesome, happy to hear that! Thanks for participating!

**Pull request closed without merging**
