### PR TITLE
Adding more speed improvements, going for first again.

### PR DESCRIPTION
**Pull request by royvanrijn**
Should work with random names as well.

Squashed all commits.

### CODE REVIEW

**Comment by thomaswue** [comment]
Did you try native image on your solution as well? I think it could very well help.

```
sdk use java 21.0.1-graal
native-image -O3 -gc=epsilon -march=native -cp target/average-1.0.0-SNAPSHOT.jar -o image_calculateaverage_royvanrijn ev.morling.onebrc.CalculateAverage_royvanrijn
./image_calculateaverage_royvanrijn
```

**Comment by royvanrijn** [comment]
@thomaswue I have tried native compilation, including copying your bash script with pgo, but it wasn't faster than just running the `java` command (on my machine).

**Comment by gunnarmorling** [comment]
@royvanrijn, can you adjust your launch script like this:

```
source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk use java 21.0.1-graal 1>&2
```

The former makes sure `sdk` is available, the latter prevents the additional output to mess with the test assertion. Thx!

**Comment by gunnarmorling** [comment]
00:07.999, wow, very nice! The implementation LGTM, can't spot anything problematic. @ebarlas, sorry, this was a short stint on #1 :) // CC @spullara

**Comment by thomaswue** [comment]
OK. Adjusted the source script also on my branch and merged with latest master @gunnarmorling.

@royvanrijn I think one main improvement here is to go for the sun.misc.Unsafe usage. Then you should get into the range where it is fast enough for native image to make a difference.

**Pull request merged**
