### PR TITLE
Stream-less? Implementation

### PR DESCRIPTION
**Pull request by yehwankim23**
Class name: `CalculateAverage_yehwankim23`

<table>
  <tr>
    <th colspan="2">System specs</th>
    <th colspan="2">yehwankim23</th>
    <th colspan="2">baseline</th>
  </tr>
  <tr>
    <td>CPU</td>
    <td>Apple M2</td>
    <td>real</td>
    <td>1:33.171</td>
    <td>real</td>
    <td>2:49.577</td>
  </tr>
  <tr>
    <td>Cores</td>
    <td>8</td>
    <td>user</td>
    <td>1:29.656</td>
    <td>user</td>
    <td>2:46.374</td>
  </tr>
  <tr>
    <td>RAM</td>
    <td>16GB</td>
    <td>sys</td>
    <td>0:03.921</td>
    <td>sys</td>
    <td>0:03.631</td>
  </tr>
</table>

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Can you please add the missing license header by running `mvn license:format` and also make sure that `./tests.sh yehwankim23` passes (please rebase to latest main to have all the latest tests before doing so). Thx!

**Review by gunnarmorling — CHANGES_REQUESTED** [review]
See above.

**Comment by yehwankim23** [comment]
I fixed the license headers, and the sample tests pass

**Comment by gunnarmorling** [comment]
03:16.334. Thx for participating.

**Pull request merged**
