### PR TITLE
Fix hundredwatt's entry on 10k dataset

### PR DESCRIPTION
**Pull request by hundredwatt**
#### Check List:
- [x] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x] Output matches that of `calculate_average_baseline.sh`
- [x] For new entries, or after substantial changes: When implementing custom hash structures, please point to where you deal with hash collisions (line number)

* Execution time:
* Execution time of reference implementation:

Use a hash function with more entropy, this fixes the stall on the 10k data set and improves performance slightly on the ~400 entry data set.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hum, hum, getting this diff now for the 10K keyset test:

```
< nsa;-20.7;10.1;39.5
---
> nsa;-21.1;10.1;39.5
```

**Comment by hundredwatt** [comment]
@gunnarmorling Hmm, I tested it like this and didn't get a diff:

```bash
$ ./create_measurements3.sh 1000000000
Generated 10,000 station names with length from 1 to 100
Wrote 50,000,000 measurements in 6,454 ms
Wrote 100,000,000 measurements in 12,645 ms
Wrote 150,000,000 measurements in 18,996 ms
Wrote 200,000,000 measurements in 25,357 ms
Wrote 250,000,000 measurements in 31,697 ms
Wrote 300,000,000 measurements in 38,032 ms
Wrote 350,000,000 measurements in 44,335 ms
Wrote 400,000,000 measurements in 50,680 ms
Wrote 450,000,000 measurements in 57,214 ms
Wrote 500,000,000 measurements in 63,675 ms
Wrote 550,000,000 measurements in 70,049 ms
Wrote 600,000,000 measurements in 76,485 ms
Wrote 650,000,000 measurements in 82,963 ms
Wrote 700,000,000 measurements in 89,224 ms
Wrote 750,000,000 measurements in 95,667 ms
Wrote 800,000,000 measurements in 102,239 ms
Wrote 850,000,000 measurements in 108,914 ms
Wrote 900,000,000 measurements in 115,421 ms
Wrote 950,000,000 measurements in 121,776 ms
Wrote 1,000,000,000 measurements in 128,210 ms
$ ln -s measurements3.txt measurements.txt
$ ./calculate_average_royvanrijn.sh > measurements3.out
$ ./test.sh hundredwatt measurements3.txt

Using java version 21.0.1-graal in this shell.
Validating calculate_average_hundredwatt.sh -- measurements3.txt
$
```

Is that the correct process for the 10k data set or did I miss something? 

I will try repeating this a few times to see if different randomly generated data sets reproduce the failing diff.

**Comment by hundredwatt** [comment]
Also noticed I had `THREAD_COUNT = Math.min(8, Runtime.getRuntime().availableProcessors());`

🤦 I removed the `min` and now my implementation should do better on the 32 core test 😄

**Comment by hundredwatt** [comment]
> I will try repeating this a few times to see if different randomly generated data sets reproduce the failing diff.

I was able to reproduce after generating a few more `mesaurements3.txt` files. Will fix 👍

**Comment by hundredwatt** [comment]
@gunnarmorling Fixed now!

My entry was skipping some measurements at chunk boundaries. The main fix was changing a `position < end` to `position <= end` 😄

**Comment by gunnarmorling** [comment]
Getting an `IOOBE` now:

```
Validating calculate_average_hundredwatt.sh -- measurements_10K_1B.txt
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:542)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at dev.morling.onebrc.CalculateAverage_hundredwatt.main(CalculateAverage_hundredwatt.java:317)
Caused by: java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer$1.apply(Buffer.java:757)
	at java.base/java.nio.Buffer$1.apply(Buffer.java:754)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:779)
	at java.base/java.nio.DirectByteBuffer.getLong(DirectByteBuffer.java:877)
	at dev.morling.onebrc.CalculateAverage_hundredwatt.processChunk(CalculateAverage_hundredwatt.java:247)
	at dev.morling.onebrc.CalculateAverage_hundredwatt.lambda$main$1(CalculateAverage_hundredwatt.java:309)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by hundredwatt** [comment]
I fixed the IOOBE issue, but am going to spend some more time testing before I ask you to eval again 😄

**Comment by hundredwatt** [comment]
I ran the rest script above for a large number of trials and did not get a failure.

@gunnarmorling please evaluate again 🙏

**Comment by gunnarmorling** [comment]
Looking good now!

```
Benchmark 1: timeout -v 300 ./calculate_average_hundredwatt.sh 2>&1
  Time (mean ± σ):      3.701 s ±  0.038 s    [User: 25.671 s, System: 0.774 s]
  Range (min … max):    3.651 s …  3.772 s    10 runs

Summary
  hundredwatt: trimmed mean 3.6980671413900006, raw times 3.71083137364,3.7155190366400004,3.68451302364,3.6595386806400003,3.65062135364,3.74212704964,3.71674824064,3.77157298564,3.69166980664,3.66358991964

Leaderboard

| # | Result (m:s.ms) | Implementation     | JDK | Submitter     | Notes     |
|---|-----------------|--------------------|-----|---------------|-----------|
|   | 00:03.698 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_hundredwatt.java)| 21.0.1-graal | [Jason Nochlin](https://github.com/hundredwatt) |  |
```

**Comment by gunnarmorling** [comment]
Hey @hundredwatt!

Congrats again on being in the Top 20 of the One Billion Row Challenge!

To celebrate this amazing achievement, I would like to send you a 1BRC t-shirt and coffee mug. To claim your prize, fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLScQLlJiI0KU8rMgoWaNAyKNO_O2Ndmjq9qnv_vmNq6rpL87LA/viewform) by Feb 18. **After** submitting the form, please provide a comment with the random value you've specified in the form, so that I know it is you who submitted it.

All data entered will solely be used in relation to processing this shipment. Shipments can be sent to any country listed [here](https://help.spreadshirt.com/hc/de/articles/207165489-Lieferzeit-Versandkosten?locale=de_DE) or [here](https://help.spreadshirt.com/hc/en-us/articles/207165489-Shipping-Times-and-Costs) (I'll use whichever one is cheaper for me to ship to your location). A big thank you to [Decodable](https://www.decodable.co/) for sponsoring these prizes!

Thanks a lot for participating in 1BRC,

--Gunnar

**Comment by hundredwatt** [comment]
Random value: 14098 14697

Thanks so much @gunnarmorling  😄

**Pull request merged**
