### PR TITLE
Small optimization for ebarlas submission.

### PR DESCRIPTION
**Pull request by ebarlas**
#### Check List:
- [x] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x] Output matches that of `calculate_average_baseline.sh`
- [x] For new entries, or after substantial changes: When implementing custom hash structures, please point to where you deal with hash collisions (line number)

* Execution time: 3.9s (down from 4.2s for 7% reduction)
* Execution time of reference implementation: 2m27s

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hum, hum, getting this test failure now:

```
Validating calculate_average_ebarlas.sh -- src/test/resources/samples/measurements-rounding.txt
2c2
< jel;-9.0;17.9;46.5
---
> jel;-9.0;18.0;46.5

FAILURE: ./test.sh ebarlas failed
```

**Comment by ebarlas** [comment]
Oh no! How strange. I'll look around. No idea what that could be.

**Comment by ebarlas** [comment]
Fixed! There was indeed a bug surfaced with that specific test and a parallelism of 32 (specific to your env).

A few lines were getting reprocessed due to a line-start book-keeping bug.

**Comment by gunnarmorling** [comment]
Ah, that's interesting. Hard to catch indeed. Could you rebase and force-push this one? I've just changed the GH Action run for PRs, so it should run tests against the submitter's entry now (wouldn't have caught this one probably as it doesn't run with 32 cores, but others it should).

**Comment by ebarlas** [comment]
I'll do that shortly!

**Comment by ebarlas** [comment]
Updated!

**Comment by gunnarmorling** [comment]
Sweet, this looks good in the CI build now: https://github.com/gunnarmorling/1brc/actions/runs/7602797389/job/20703748694. This should save some time going forward.

**Comment by gunnarmorling** [comment]
00:03.990 now, nice!

**Pull request merged**
