### PR TITLE
GraalVM native image from QBos07

### PR DESCRIPTION
**Pull request by QBos07**
#### Check List:
- [X] Tests pass (`./test.sh qbos07`)
- [X] All formatting changes by the build are committed
- [X] Output matches that of calculate_average_baseline.sh
* Execution time: 2:01,05 [1] [2]
* Execution time of reference implementation: ~4:25 [2]
 
[1] Had to change to optimized code to be able to run it on my 4 core machine. This makes it heavly non-optimal on my pc.
[2] All files were on a slow HDD (due to size) wich espacially impacts the optimized version.
**(I expact at least a double in speed on the test machine)**

*No code was changed! Only compilation is affected.* Credit goes to Ray van Riju for the implementation.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey, could you please re-organize the scripts following the structure we've adopted since then. I.e. there should be a script prepare_QBos07.sh which does the build and SDKMan config and the calculate_average_QBos07.sh script should invoke native or JVM impl based on the native binary's presence. You can find an example in Roy's and Thomas' impl (at the top of the leaderboard right now). Thx!

**Review by gunnarmorling — CHANGES_REQUESTED** [review]
See above.

**Comment by QBos07** [comment]
Now good?

**Comment by gunnarmorling** [comment]
Hum, hum, getting this error now:

```
> java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Based on the linker command output, possible reasons for this include:
1. It appears as though libz.a is missing. Please install it.

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--version-script,/tmp/SVM-14402374923086019117/exported_symbols.list -Wl,-x -o /home/build/projects/eval/1brc/target/samplerun_qbos07 samplerun_qbos07.o /home/build/.sdkman/candidates/java/21.0.1-graal/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/build/.sdkman/candidates/java/21.0.1-graal/lib/static/linux-amd64/glibc/libnet.a /home/build/.sdkman/candidates/java/21.0.1-graal/lib/static/linux-amd64/glibc/libnio.a /home/build/.sdkman/candidates/java/21.0.1-graal/lib/static/linux-amd64/glibc/libjava.a /home/build/.sdkman/candidates/java/21.0.1-graal/lib/static/linux-amd64/glibc/libzip.a /home/build/.sdkman/candidates/java/21.0.1-graal/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-14402374923086019117 -L/home/build/.sdkman/candidates/java/21.0.1-graal/lib/static/linux-amd64/glibc -L/home/build/.sdkman/candidates/java/21.0.1-graal/lib/svm/clibraries/linux-amd64 -Wl,-Bstatic -lz -Wl,-Bdynamic -ldl -Wl,-Bdynamic -lpthread -Wl,-Bdynamic -lrt -static-libgcc

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-host-pie --enable-host-bind-now --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --enable-initfini-array --without-isl --enable-multilib --with-linker-hash-style=gnu --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_64=x86-64-v2 --with-arch_32=x86-64 --build=x86_64-redhat-linux --with-build-config=bootstrap-lto --enable-link-serialization=1
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.1 20230605 (Red Hat 11.4.1-2) (GCC)
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/11/:/usr/libexec/gcc/x86_64-redhat-linux/11/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/11/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/11/:/usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/11/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/build/projects/eval/1brc/target/samplerun_qbos07' '-v' '-L/tmp/SVM-14402374923086019117' '-L/home/build/.sdkman/candidates/java/21.0.1-graal/lib/static/linux-amd64/glibc' '-L/home/build/.sdkman/candidates/java/21.0.1-graal/lib/svm/clibraries/linux-amd64' '-static-libgcc' '-mtune=generic' '-march=x86-64-v2' '-dumpdir' '/home/build/projects/eval/1brc/target/samplerun_qbos07.'
 /usr/libexec/gcc/x86_64-redhat-linux/11/collect2 -plugin /usr/libexec/gcc/x86_64-redhat-linux/11/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper -plugin-opt=-fresolution=/tmp/ccsdSutm.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /home/build/projects/eval/1brc/target/samplerun_qbos07 -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/11/crtbegin.o -L/tmp/SVM-14402374923086019117 -L/home/build/.sdkman/candidates/java/21.0.1-graal/lib/static/linux-amd64/glibc -L/home/build/.sdkman/candidates/java/21.0.1-graal/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/11 -L/usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/11/../../.. --gc-sections --version-script /tmp/SVM-14402374923086019117/exported_symbols.list -x samplerun_qbos07.o /home/build/.sdkman/candidates/java/21.0.1-graal/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/build/.sdkman/candidates/java/21.0.1-graal/lib/static/linux-amd64/glibc/libnet.a /home/build/.sdkman/candidates/java/21.0.1-graal/lib/static/linux-amd64/glibc/libnio.a /home/build/.sdkman/candidates/java/21.0.1-graal/lib/static/linux-amd64/glibc/libjava.a /home/build/.sdkman/candidates/java/21.0.1-graal/lib/static/linux-amd64/glibc/libzip.a /home/build/.sdkman/candidates/java/21.0.1-graal/lib/svm/clibraries/linux-amd64/libjvm.a -Bstatic -lz -Bdynamic -ldl -Bdynamic -lpthread -Bdynamic -lrt -lgcc -lgcc_eh -lc -lgcc -lgcc_eh /usr/lib/gcc/x86_64-redhat-linux/11/crtend.o /usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64/crtn.o
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
```

Seems some package is missing? Not sure which one though.

Taking a step back, what are we actually trying to do here? This invoke's @royvanrijn's implementation, not yours? Roy has added native compilation by now, too. So I think we could close this one here?

**Comment by gunnarmorling** [comment]
Ah yeah, seeing it in the submission text now, this was meant to add native image support to Roy's implementation. I am going to close this one in this light, given Roy's submission already has that. Thanks nevertheless!

**Comment by QBos07** [comment]
I had some more optimized flags than him.
It‘s missing a static zlib for linking. Statically linking gives some minuscule amount during initializing.

Am 11.01.2024 um 20:31 schrieb Gunnar Morling ***@***.******@***.***>>:


Closed #173<https://github.com/gunnarmorling/1brc/pull/173>.

**Comment by gunnarmorling** [comment]
Ok, gotcha. If you feel it's worth it, perhaps send a PR to update Roy's prepare script itself? If it's just a few ms, i.e. within error margin of what we can measure, then it may not be worth the trouble. Specifically, I'm not sure which package I need to install on CentOS Stream for getting that static zlib thing.

**Pull request closed without merging**
