### PR TITLE
Tuning and subprocess spawn for thomaswue

### PR DESCRIPTION
**Pull request by thomaswue**
#### Check List:
- [x] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x] Output matches that of `calculate_average_baseline.sh`
- [x] For new entries, or after substantial changes: When implementing custom hash structures, please point to where you deal with hash collisions (line number)

* Execution time: 0.47s
* Execution time of reference implementation: 120.37s

Apart from some minor tunings (which should amount to ~3%), this PR now creates a subprocess to do the actual work. The main process returns immediately once the output is calculated. The OS clean up unmapping the pages that were mapped in continues in the background process. The code for this is just a few lines of Java Process API in the spawnWorker method. The subprocess is started with the exact same command as the original process, but with a "--worker" argument.

I have also updated the Graal version to the latest CPU release (21.0.2).

### CODE REVIEW

**Comment by artsiomkorzun** [comment]
@thomaswue so is it officially allowed?

**Comment by thomaswue** [comment]
@gunnarmorling said he is considering to allow it. Let's see how it works with the official evaluation setup.

**Comment by gunnarmorling** [comment]
00:02.195, very nice! 2 sec is in sight :) Clearly on #1 now, but @abeobk and @artsiomkorzun haven't applied the same trick yet, so...

```
Benchmark 1: timeout -v 300 ./calculate_average_thomaswue.sh 2>&1
  Time (mean ± σ):      2.194 s ±  0.022 s    [User: 0.002 s, System: 0.003 s]
  Range (min … max):    2.154 s …  2.225 s    10 runs

Summary
  thomaswue: trimmed mean 2.19571922781, raw times 2.15433713906,2.20952494606,2.17099705406,2.20550811606,2.19039166406,2.22460009706,2.20810557306,2.17378339906,2.20745058306,2.19999248706

Leaderboard

| # | Result (m:s.ms) | Implementation     | JDK | Submitter     | Notes     |
|---|-----------------|--------------------|-----|---------------|-----------|
|   | 00:02.195 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_thomaswue.java)| 21.0.2-graal | [Thomas Wuerthinger](https://github.com/thomaswue) | GraalVM native binary |
```

**Comment by thomaswue** [comment]
Cool, thank you! Let's gooo ;-)

**Pull request merged**
