### PR TITLE
test: add script to test all implementations

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
The script tests all implementations and prints PASS or FAIL status. In case of failure it also prints implementation output to stderr.

This will be handy for adding new test samples.

Show test statuses and omit failing output:
```sh
$ ./test_all.sh 2>/dev/null
PASS artsiomkorzun
PASS baseline
PASS bjhara
PASS criccomini
FAIL ddimtirov
FAIL ebarlas
PASS filiphr
FAIL itaske
PASS khmarbaise
FAIL kuduwa-keshavram
FAIL lawrey
PASS padreati
FAIL palmr
PASS richardstartin
FAIL royvanrijn
FAIL seijikun
PASS spullara
PASS truelive
```

Show only passing implementations:
```
$ ./test_all.sh 2>/dev/null | grep PASS | cut -d' ' -f2
artsiomkorzun
baseline
bjhara
criccomini
filiphr
khmarbaise
padreati
richardstartin
spullara
truelive
```

For #61

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Ah, that is _really_ good! Thank you so much, really appreciate it. I'm surprised to see lawrey fail, that LGTM here 🤔 .

**Comment by AlexanderYastrebov** [comment]
>  I'm surprised to see lawrey fail

Might be due to my setup. E.g. in my fork I had to fix scripts that use sdk like https://github.com/gunnarmorling/1brc/commit/71a4ee89b1e21715772d0d9e14be46e7d5521785

**Comment by gunnarmorling** [comment]
It was caused by the GC logging he did. I've removed that one, so it's showing `PASS` now, as expected.

**Comment by AlexanderYastrebov** [comment]
Do others pass in your environment? Maybe you could run test_all.sh and file an issue for each failure?

**Comment by gunnarmorling** [comment]
Done, see https://github.com/gunnarmorling/1brc/issues/284 ff. (there's a few more failures but these authors have pending PRs already, so I reckon any failures have been fixed there already.

**Pull request merged**
