### PR TITLE
Bug fixes, readability and Graal VM.

### PR DESCRIPTION
**Pull request by japplis**
#### Check List:
- [x] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x] Output matches that of `calculate_average_baseline.sh`
- [x] For new entries, or after substantial changes: When implementing custom hash structures, please point to where you deal with hash collisions (line number)

* Execution time: same time (18" on 2016 desktop)
* Execution time of reference implementation: 3'30"

### CODE REVIEW

**Comment by gunnarmorling** [comment]
> [update file permission](https://github.com/gunnarmorling/1brc/pull/537/commits/dde7856df593dee8ae813f1cf1c38e10b99a246d)

Nice, the first bug caught by running tests on CI now :)

**Comment by gunnarmorling** [comment]
This one has huge outliers for some reason, does that happen on your machine too? Would be interesting to know why.

```
Benchmark 1: timeout -v 300 ./calculate_average_japplis.sh 2>&1
  Time (mean ± σ):     13.736 s ±  8.038 s    [User: 105.089 s, System: 2.228 s]
  Range (min … max):    9.765 s … 28.107 s    5 runs

  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet system without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

Summary
  japplis: trimmed mean 10.269811343886667, raw times 10.05761184322,10.43402437022,10.31779781822,9.76453012922,28.10696535222

Leaderboard

| # | Result (m:s.ms) | Implementation     | JDK | Submitter     | Notes     |
|---|-----------------|--------------------|-----|---------------|-----------|
|   | 00:10.269 | [link](https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_japplis.java)| 21.0.1-graal | [Anthony Goubard](https://github.com/japplis) |  |
```

**Comment by japplis** [comment]
Yes, it was also very unstable on my system (2016 Windows desktop). The first 2 runs around 27" then the next 2 runs around 18".
I've removed the file as it doesn't improve performance and it's unstable.

**Comment by gunnarmorling** [comment]
00:10.179, i.e. a tad slower. Do you want to have it merged indeed?

**Comment by japplis** [comment]
Yes, let's merge it. I guess the difference is the machine fluctuation. But there is a small bug fix in this MR.

**Pull request closed without merging**
