### PR TITLE
Use proper hash key collision detection scheme.

### PR DESCRIPTION
**Pull request by ebarlas**
This is a replacement for PR https://github.com/gunnarmorling/1brc/pull/74.

This change is primarily about compliance. The prior version of my `ebarlas` submission didn't adequately handle theoretical hash key collisions. The current version now does that with an open addressing scheme.

Changes here also include various unrelated adjustments.

Implementation class: `CalculateAverage_ebarlas`

The exec time on an AWS EC2 `c5.2xlarge` with 8 vCPU is slightly higher than before, now clocking in at 10.1s. However, still noticeably lower than on the CX33 target env, interestingly.

```
real	0m10.192s
user	1m19.001s
sys	0m0.580s
```

This submission is still configured to run on GraalVM CE.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@ebarlas, could you run this one:

```
./test.sh ebarlas
```

This is a little test suite I've added and there seem to be some failures. Thanks!

**Comment by ebarlas** [comment]
Yes! I'll take a look now.

**Comment by ebarlas** [comment]
Ah, the partitioning isn't working properly when it happens _within a line_! Getting that fixed now.

**Comment by ebarlas** [comment]
Fixed, @gunnarmorling!

**Comment by gunnarmorling** [comment]
Ah, gasp, just ran this one a minute ago. Do you plan to push further updates, @ebarlas?

**Comment by ebarlas** [comment]
Sorry about that! Not right at this _moment_.

**Comment by ebarlas** [comment]
It feels like we need a Discord server with all of the discussions happening.

**Comment by gunnarmorling** [comment]
Haha, yeah. Had I only known... ;)

**Comment by gunnarmorling** [comment]
0m14.476s. Nice!

**Comment by gunnarmorling** [comment]
The hashing scheme LGTM now too. Btw. thanks a lot for going through the iterative refinement of requirements today, appreciate the patience and quick turn around times to smoothen all that out.

**Comment by ebarlas** [comment]
You're welcome! Needless to say, I've been having a lot of fun with this. So, thank _you_!

**Comment by ebarlas** [comment]
By the way, is `0m14.476s` the official time? Just notice a higher figure on the leaderboard.

**Comment by ebarlas** [comment]
@gunnarmorling, is there anything additional I need to do to ensure the my solution is running with GraalVM?

I'm trying to understand the timing discrepancy I'm seeing and I thought perhaps my solution isn't actually running with GraalVM. Do I need an install command prior? I noticed the other competitors are apparently still relying on your manual config for GraalVM.

Relatedly, is the non-CE edition of Graal accessible?

```
sdk use java 21.0.1-graal
```

**Comment by gunnarmorling** [comment]
> By the way, is 0m14.476s the official time? Just notice a higher figure on the leaderboard.

Yeah, still had to update it.

> @gunnarmorling, is there anything additional I need to do to ensure the my solution is running with GraalVM?

Not really, it's a manual (and thus, yes, error-prone process). I'm quite confident I did it right. But if you'd like to explore how to automate this task (see https://github.com/gunnarmorling/1brc/issues/88), this would be awesome.

**Comment by gunnarmorling** [comment]
Probably just `source "$HOME/.sdkman/bin/sdkman-init.sh"` at the beginning of your launch script should do the trick.

**Pull request merged**
