### PR TITLE
Mahadev virtual thread 1brc

### PR DESCRIPTION
**Pull request by mahadev-k**
#### Check List:
- [x] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs) `./test.sh mahadev_k `
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable `./calculate_average_mahadev_k.sh`
- [x] Output matches that of `calculate_average_baseline.sh`
- [x] For new entries, or after substantial changes: When implementing custom hash structures, please point to where you deal with hash collisions (line number)

* Execution time: 1.5min Max
* Execution time of reference implementation:

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Please make sure that the scripts match your actual GH account name ("-" vs. "_"). Also note that new entries at this point should come in at ~10 sec to keep things manageable with the large number of entries so far.

**Comment by mahadev-k** [comment]
I have updated the names as per the GH username.
`calculate_average_mahadev-k.sh`
`./prepare_mahadev-k.sh `

Sorry for the inconvenience. Please review and build the project again.

**Comment by gunnarmorling** [comment]
Please make the scripts executable.

**Comment by mahadev-k** [comment]
Added chmod +x for the prepare and calculate mahadev-k .sh files.

**Comment by gunnarmorling** [comment]
01:53.208.

**Comment by mahadev-k** [comment]
In the mac book pro - 32GB RAM and Apple M2 this takes only around 60-70 seconds though..

**Pull request merged**
