### PR TITLE
Initial solution by raipc

### PR DESCRIPTION
**Pull request by raipc**
#### Check List:
- [x] Tests pass (`./test.sh <username>`)
- [x] All formatting changes by the build are committed
- [x] Output matches that of calculate_average_baseline.sh
* Execution time: 0m11.721s
* Execution time of reference implementation: 4m49.937s

My solution is based on implementing fork/join tasks and using JVM internals to access vectorized intrinsics.

### CODE REVIEW

**Comment by raipc** [comment]
Added custom hash map -- decreased exec time to  0m8.542s

**Review by gunnarmorling — CHANGES_REQUESTED** [review]
Can you please run `mvn license:format` and make the launch script executable. Thx!

**Comment by raipc** [comment]
@gunnarmorling I fixed the script and license. Could you merge it, please?

**Comment by gunnarmorling** [comment]
Have some patience, please :) I'm swamped with submissions, and there's an issue with the evaluation environment to sort out. I'll get to this in due course. Thx for hanging in!

**Comment by gunnarmorling** [comment]
00:10.473. Thx for participating!

**Pull request merged**
