### PR TITLE
filiphr first submission

### PR DESCRIPTION
**Pull request by filiphr**
Really interesting and fun challenge @gunnarmorling.

I gave it a go, first implementation using Shenandoah GC (reduces GC pauses significantly) and uses parallel iteration.

My implementation is: [CalculateAverage_filiphr.java]
I used OpenJDK Runtime Environment Zulu21.30+15-CA (build 21.0.1+12-LTS) (21.0.1-zulu)

On Macbook Pro (8 core Intel 64 GB RAM) it runs in +/- 1m40s, the reference implementation runs in +/- 4m9s

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Nice one, thanks a lot! Will evaluate this one tomorrow, first need to install that Zulu JDK.

**Comment by filiphr** [comment]
Thanks. It doesn't have to be Zulu though. It needs a JDK that has Shenandoah GC, the ones provided by Oracle do not have it (Graal, Oracle JDK and Open JDK). Zulu, Temurin, RedHat, SAP have it (in case it is easier for you to use one of the others)

**Comment by filiphr** [comment]
Hey @lobaorn, it would for sure be interesting to try out a different build from https://builds.shipilev.net/. Which one will you suggest me to try out?

I've been also working on using memory mapped files locally and it seems like the GC is not making any special differences now.

**Comment by filiphr** [comment]
Thanks @lobaorn, I'll check Twitter and the Comments in #15 as well.

I've done some rework on this using memory mapped files thanks @bjhara and @royvanrijn for their submissions, I learned something new. 

Changed to use `BigDecimal` parsing instead of `Double.parseBoolean`, that improves a bit the speed as well.

With the updates it now runs in ~35s on my machine

**Comment by gunnarmorling** [comment]
@filiphr, if any of the distros available from SDKMan can be used, could you add a line [like this](https://github.com/gunnarmorling/1brc/pull/45) to your launch script?

**Comment by filiphr** [comment]
@gunnarmorling, done. I've added `sdk use java 21.0.1-graal`. Using the Graal CE edition makes no difference for me. 

If it isn't possible to use Oracle GraalVM (it is available on SDKMan) then it is fine to just run this with the default JDK

**Comment by filiphr** [comment]
Nice, thanks for merging it. Such a fun experience. Will ty to speed it up a bit more :)

**Pull request merged**
