### PR TITLE
Add entry from fragmede.

### PR DESCRIPTION
**Pull request by fragmede**
Hi,

This entry uses a custom atoi function to use integer math instead of floating point math.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thanks for participating! Could you please run `./test.sh fragmede` and verify that there are no test failures before we evaluate (it's gonna be part of the CI build eventually)? Thx!

**Comment by fragmede** [comment]
```
fragmede@samairmac:(main)~/projects/1billionrows/1brc$ ./test.sh fragmede
Validating calculate_average_fragmede.sh -- src/test/resources/samples/measurements-1.txt

real	0m0.158s
user	0m0.055s
sys	0m0.032s
Validating calculate_average_fragmede.sh -- src/test/resources/samples/measurements-10.txt

real	0m0.067s
user	0m0.049s
sys	0m0.015s
Validating calculate_average_fragmede.sh -- src/test/resources/samples/measurements-10000-unique-keys.txt

real	0m0.112s
user	0m0.145s
sys	0m0.021s
Validating calculate_average_fragmede.sh -- src/test/resources/samples/measurements-2.txt

real	0m0.073s
user	0m0.056s
sys	0m0.015s
Validating calculate_average_fragmede.sh -- src/test/resources/samples/measurements-20.txt

real	0m0.067s
user	0m0.064s
sys	0m0.016s
Validating calculate_average_fragmede.sh -- src/test/resources/samples/measurements-3.txt

real	0m0.087s
user	0m0.068s
sys	0m0.019s
Validating calculate_average_fragmede.sh -- src/test/resources/samples/measurements-boundaries.txt

real	0m0.073s
user	0m0.071s
sys	0m0.018s
fragmede@samairmac:(main)~/projects/1billionrows/1brc$```

Seems good to me!

**Comment by fragmede** [comment]
Rebased on latest and [updated workflow file to run test.sh for the repository owner](https://github.com/fragmede/1brc/blob/main/.github/workflows/maven.yml) (me in this case).

[successful build/test run](https://github.com/fragmede/1brc/actions/runs/7417098298)

**Comment by gunnarmorling** [comment]
03:42.297. Thx for participating!

**Pull request merged**
