### PR TITLE
Added CalculateAverage_lawrey.java

### PR DESCRIPTION
**Pull request by peter-lawrey**
4325 ms on my Ryzen 5950X
No GC with -Xmx99m

### CODE REVIEW

**Comment by peter-lawrey** [comment]
Compared result with the reference implementation.

**Comment by gunnarmorling** [comment]
Thanks a lot! Could you please add a launch script, as described in the README?

**Comment by peter-lawrey** [comment]
I have added a script, `time` reported 4.9s elapse.

**Comment by gunnarmorling** [comment]
00:17.905, nice!

**Pull request merged**
